import base64

# Favicon simples em base64 (16x16 pixels, ícone de karatê/dojo)
favicon_base64 = """
AAABAAEAEBAAAAAAAABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA
/38AAP9/AAAAAAAAAP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA
/38AAP9/AAD/fwAAAAAAAP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/
fwAA/38AAP9/AAD/fwAAAAAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA/38A
AP9/AAD/fwAA/38AAP9/AAAAAAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/
fwAA/38AAP9/AAD/fwAA/38AAAAAAP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA/38A
AP9/AAD/fwAA/38AAP9/AAD/fwAAAAAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/
fwAA/38AAP9/AAD/fwAA/38AAP9/AAAAAAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA/38A
AP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAAAAAP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/
fwAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAAAAAA/38AAP9/AAD/fwAA/38AAP9/AAD/fwAA/38A
AP9/AAD/fwAA/38AAP9/AAD/fwAA/38AAP9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//
AAD//wAA//8AAA==
"""

def create_favicon_file():
    """Cria arquivo favicon.ico a partir do base64"""
    try:
        # Decodificar base64
        favicon_data = base64.b64decode(favicon_base64.strip())
        
        # Salvar como arquivo .ico
        with open('favicon.ico', 'wb') as f:
            f.write(favicon_data)
        
        print("✅ Favicon criado com sucesso!")
        return True
    except Exception as e:
        print(f"❌ Erro ao criar favicon: {e}")
        return False

if __name__ == "__main__":
    create_favicon_file()