# TEMPLATE - RENOMEIE PARA secrets.toml E CONFIGURE
[credentials]
usernames = { admin = { email = "admin@dojo.com", name = "Administrador", password = "$2b$12$HASH_AQUI" } }

[cookie]
name = "dojo_auth_cookie"
key = "SUBSTITUA_POR_CHAVE_ALEATORIA_FORTE_64_CHARS_MINIMO_EXEMPLO"
expiry_days = 7

[roles]
admin = "admin"

# Firebase Configuration
[firebase]
project_id = "SEU_PROJECT_ID_AQUI"
credentials_path = "caminho/para/service-account-key.json"

# Environment
[environment]
debug = true